### ISSUE TITLE
Conditions can be used inside of conditional functions

### ISSUE THREAD

**Issue by jpb** [jpb/laundry#14]
```
Conditions:
  Bar: true
  Baz: true
  Foo: !And [Bar, Baz]
```

Produces:

```
Root.Conditions.Foo.And.0: must be a Boolean, got "Bar"
Root.Conditions.Foo.And.1.Not.0: must be a Boolean, got "Baz"
```
