### ISSUE TITLE
IAM Policy Document Resource format

### ISSUE THREAD

**Issue by jpb** [jpb/laundry#2]
Laundry did not produce an error for:

Example template:

```
Resources:
  Policy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: LoggingRolePolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - logs:CreateLogGroup
            Effect: Allow
            Resource:
              - some-string
```

Error from CloudFormation:

```
Resource ... must be in ARN format or "*".
```
