### ISSUE TITLE
Lambda Function Role format

### ISSUE THREAD

**Issue by jpb** [jpb/laundry#3]
Laundry did not produce an error for:

Example template:

```
Resources:
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      FunctionName: !Ref AWS::StackName
      Role: some-string
      Runtime: nodejs8.10                                                                                                               
      Timeout: 10
      Code:                                                                                                                               
        ZipFile: !Ref Code
```

Error from CloudFormation:

```
1 validation error detected: Value
                          'some-string' at 'role' failed to
                          satisfy constraint: Member must satisfy regular expression
                          pattern:
                          arn:(aws[a-zA-Z-]*)?:iam::\d{12}:role/?[a-zA-Z_0-9+=,.@\-_/]+
```
