### ISSUE TITLE
Ignore lint checks via metadata

### ISSUE THREAD

**Issue by jpb** [jpb/laundry#4]
Ignore a specific property:

```
Metadata:
  LaundryIgnore:
    'MyTopic.Properties.Name':
      - RequriedResourcePropertyValidator
Resources:
  MyTopic:
    Type: AWS::SNS::Topic
```

Ignore with glob:

```
Metadata:
  LaundryIgnore:
    'Resources.MyTopic.*':
      - RequriedResourcePropertyValidator
    '*.Name.*':
      - RequriedResourcePropertyValidator
Resources:
  MyTopic:
    Type: AWS::SNS::Topic
```

Ignore for everything:

```
Metadata:
  LaundryIgnore:
    '*':
      - RequriedResourcePropertyValidator
Resources:
  MyTopic:
    Type: AWS::SNS::Topic
```

Ignore for a resource:

```
Resources:
  MyTopic:
    Metadata:
      LaundryIgnore:
        - RequriedResourcePropertyValidator
    Type: AWS::SNS::Topic
```
